name: CI Development

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --no-build-isolation -r requirements.txt

      - name: Analizar código con Black
        run: |
          pip install black
          black --check .

      - name: Analizar imports con isort
        run: |
          pip install isort
          isort --check-only .

      - name: Lint con Pylint
        run: |
          pip install pylint
          pylint api ml_pipeline tests --exit-zero

      - name: Ejecutar pruebas unitarias
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings
