name: CI Production

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install --no-build-isolation -r requirements.txt

      - name: Ejecutar pruebas
        run: |
          pytest --disable-warnings --maxfail=1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform PROD
        working-directory: terraform/env/prod
        run: terraform init

      - name: Terraform Plan PROD
        working-directory: terraform/env/prod
        run: terraform plan

      - name: Terraform Apply PROD
        working-directory: terraform/env/prod
        run: terraform apply -auto-approve
